// ./src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { TooltipProvider } from "@/components/ui/tooltip";
import ClientLayout from "@/helpers/ClientLayout";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "HWM",
  description: "Generated by Team Pseudo Coder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <TooltipProvider>
          <body className={inter.className}>
            <ClientLayout>
              {children}
            </ClientLayout>
          </body>
        </TooltipProvider>
      </AuthProvider>
    </html>
  );
}